version: '3'
services:
  www:
    image: tokumeikoi/lcrp
    volumes:
      - '/app/v2board/www:/www'
      - '/app/v2board/wwwlogs:/wwwlogs'
      - '/app/v2board/caddy.conf:/run/caddy/caddy.conf'
      - '/app/v2board/supervisord.conf:/run/supervisor/supervisord.conf'
      - '/app/v2board/crontabs.conf:/etc/crontabs/root'
      - '/app/v2board/.caddy:/root/.caddy'
#    ports:
#      - '80:80'
#      - '443:443'
    restart: always
  mysql:
    image: mysql:5.7.29
    volumes:
      - './mysql:/var/lib/mysql'
    restart: always
    environment: 
      MYSQL_ROOT_PASSWORD: v2boardisbest
      MYSQL_DATABASE: v2board
