version: '3'
services:
  www:
    image: tokumeikoi/lcrp
    volumes:
      - './www:/www'
      - './wwwlogs:/wwwlogs'
      - './caddy.conf:/run/caddy/caddy.conf'
      - './supervisord.conf:/run/supervisor/supervisord.conf'
      - './crontabs.conf:/etc/crontabs/root'
      - './.caddy:/root/.caddy'
#    ports:
#      - '80:80'
#      - '443:443'
    restart: always
    networks:
      - dokploy-network
      - v2board-network

  mysql:
    image: mysql:5.7.29
    volumes:
      - './mysql:/var/lib/mysql'
    restart: always
    environment: 
      MYSQL_ROOT_PASSWORD: v2boardisbest
      MYSQL_DATABASE: v2board
    networks:
      - v2board-network

#  redis:
#    image: redis:7.0-alpine
#    restart: always
#    volumes:
#      - './redis-data:/data'
#    networks:
#      - v2board-network

networks:
  dokploy-network:
    external: true
  v2board-network:
    driver: bridge
